inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - '*.spec'
    - 'doc/plugins/**'
    - 'locale/**'
    - 'vendor/**/*'

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Naming/FileName:
  Exclude:
    - 'db/seeds.d/*'

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/orchestration/*.rb'

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
